version: '3'

services:
  web:
    image: zhouyu2156/myblog:latest
    ports:
      - '5000:5000'
    volumes:
      - myblog-data:/myblog/instance
      - myblog-uploads:/myblog/app/static/uploads
      - ./migrations:/myblog/migrations
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - SECRET_KEY=your-secret-key
      - MAIL_SERVER=smtp.qq.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
      - MAIL_USERNAME=1043744584@qq.com
      - MAIL_PASSWORD=idyvggfovuwybfid
      - DATABASE_URL=sqlite:////myblog/instance/blog.db
    restart: always

  redis:
    image: redis:6
    volumes:
      - redis-data:/data
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - '80:5000'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - myblog-uploads:/myblog/app/static/uploads:ro
    depends_on:
      - web
    restart: always

volumes:
  myblog-data:
  myblog-uploads:
  redis-data:
